import React, { useState, useEffect } from 'react';
import { useAuth } from '@/context/AuthContext';
import { getHRMSettings } from '@/lib/hrmStorage';
import { getLeads, addLead } from '@/lib/crmStorage';
import { Lead } from '@/types/crm';
import { Sparkles, Download, Check, Plus, Search, Loader2 } from 'lucide-react';

interface Props {
  showToast: (msg: string, type: 'success'|'error') => void;
}

const PREDEFINED_PROMPTS = [
  { category: 'E-commerce', label: 'Fashion / Clothing' },
  { category: 'E-commerce', label: 'Tech & Gadgets' },
  { category: 'E-commerce', label: 'Groceries' },
  { category: 'E-commerce', label: 'Beauty & Cosmetics' },
  { category: 'E-commerce', label: 'Home & Furniture' },
  { category: 'E-commerce', label: 'Books & Stationery' },
  { category: 'E-commerce', label: 'Sports & Fitness' },
  { category: 'E-commerce', label: 'Toys & Kids' },
  { category: 'E-commerce', label: 'Handicrafts' },
  { category: 'E-commerce', label: 'Jewelry' },
  { category: 'Restaurant', label: 'Cafe & Coffee Shop' },
  { category: 'Restaurant', label: 'Fine Dining' },
  { category: 'Restaurant', label: 'Fast Food' },
  { category: 'Restaurant', label: 'Cloud Kitchen' },
  { category: 'Restaurant', label: 'Bakery & Pastry' },
  { category: 'Restaurant', label: 'Pizza & Burger' },
  { category: 'Restaurant', label: 'Seafood' },
  { category: 'Restaurant', label: 'Steakhouse' },
  { category: 'Restaurant', label: 'Juice Bar' },
  { category: 'Restaurant', label: 'Buffet' },
];

export const CRMAILeadPage: React.FC<Props> = ({ showToast }) => {
  const { user } = useAuth();
  const [aiEnabled, setAiEnabled] = useState(false);
  const [apiKey, setApiKey] = useState('');
  const [activeTab, setActiveTab] = useState<'E-commerce' | 'Restaurant'>('E-commerce');
  
  const [customPrompt, setCustomPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedLeads, setGeneratedLeads] = useState<Partial<Lead>[]>([]);
  
  const [isImporting, setIsImporting] = useState(false);

  useEffect(() => {
    if (user) {
      getHRMSettings(user.uid).then(settings => {
        if (settings) {
          setAiEnabled(settings.aiEnabled || false);
          setApiKey(settings.geminiApiKey || '');
        }
      });
    }
  }, [user]);

  const handleGenerate = async (promptText: string) => {
    if (!aiEnabled || !apiKey) {
      showToast("Please enable AI and add your Gemini API Key in Settings.", "error");
      return;
    }

    setIsGenerating(true);
    setGeneratedLeads([]);

    try {
      const systemPrompt = `
      You are a specialized lead generation AI. Generate a list of 5 to 10 highly realistic (or real) business leads for the following request.
      Context area: Bangladesh (Dhaka preferred but can be anywhere).
      The output MUST be a strict JSON array of objects matching this exact structure:
      [
        {
          "businessName": "Company Name",
          "ownerName": "Owner Name (realistic)",
          "phone": "017...",
          "locationArea": "Area, City",
          "businessType": "Restaurant or E-commerce or Retail etc",
          "businessSubType": "Specific subtype",
          "painPoint": "Why they might need a software system",
          "notes": "Generated by AI prospector"
        }
      ]
      
      Request: Find leads for ${promptText}
      `;

      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: systemPrompt }] }],
          generationConfig: { response_mime_type: "application/json" }
        })
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error?.message || "API Error");
      
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (text) {
        const parsed = JSON.parse(text) as Partial<Lead>[];
        setGeneratedLeads(parsed);
        showToast(`Generated ${parsed.length} leads successfully!`, "success");
      }
    } catch (err) {
      console.error(err);
      showToast("Failed to generate leads. " + (err as Error).message, "error");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleImport = async () => {
    if (!user || generatedLeads.length === 0) return;
    setIsImporting(true);

    try {
      // Fetch existing leads to check duplicates
      const existingLeads = await getLeads(user.uid);
      let importedCount = 0;
      let skippedCount = 0;

      for (const gl of generatedLeads) {
        // Check duplicate by name (case insensitive) or phone
        const isDuplicate = existingLeads.some(el => 
          (el.businessName.toLowerCase() === (gl.businessName || '').toLowerCase()) ||
          (el.phone && gl.phone && el.phone === gl.phone)
        );

        if (isDuplicate) {
          skippedCount++;
        } else {
          // Add as new lead
          await addLead({
            userId: user.uid,
            dateAdded: new Date().toISOString().split('T')[0],
            businessName: gl.businessName || 'Unknown Business',
            ownerName: gl.ownerName || '',
            phone: gl.phone || '',
            messenger: '',
            locationArea: gl.locationArea || '',
            branchCount: '1',
            businessType: gl.businessType || 'Other',
            businessSubType: gl.businessSubType || '',
            currentPos: '',
            websiteUrl: '',
            facebookUrl: '',
            instagramUrl: '',
            painPoint: gl.painPoint || '',
            leadSource: 'AI Generated',
            firstContactDate: '',
            responseReceived: false,
            leadStatus: 'NEW',
            demoDate: '',
            demoStatus: '',
            proposalSent: false,
            followUpDate: '',
            followUpCount: 0,
            objection: '',
            expectedClosingDate: '',
            dealValue: 0,
            salesStatus: 'Pending',
            lostReason: '',
            nextAction: '',
            notes: gl.notes || 'Imported from AI Prospecting',
            leadPriority: 'COLD',
          });
          importedCount++;
        }
      }

      showToast(`Imported ${importedCount} leads. Skipped ${skippedCount} duplicates.`, "success");
      setGeneratedLeads([]); // Clear after import
    } catch (err) {
      console.error(err);
      showToast("Failed to import leads.", "error");
    } finally {
      setIsImporting(false);
    }
  };

  if (!aiEnabled) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center space-y-4">
        <Sparkles className="w-12 h-12 text-slate-700 dark:text-slate-300" />
        <h2 className="text-xl font-bold text-white">AI Prospecting Disabled</h2>
        <p className="text-slate-400 text-sm max-w-md">Please go to Settings & AI, enable the AI Assistant, and provide your Gemini API Key to use this feature.</p>
      </div>
    );
  }

  return (
    <div className="w-full mx-auto space-y-6 pb-24">
      {/* Header */}
      <div className="bg-slate-900 p-4 sm:p-5 rounded-md border border-slate-800 shadow-md flex flex-wrap items-center justify-between gap-4 text-white">
        <div>
          <div className="flex flex-wrap items-center gap-2.5">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
            <h2 className="text-lg font-bold text-white">AI Prospecting</h2>
          </div>
          <p className="text-xs text-slate-400 mt-1">Discover new leads automatically using Gemini AI.</p>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Column: Prompts */}
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-slate-900 rounded-md border border-slate-800 shadow-md p-5">
            <h3 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <Search className="w-4 h-4 text-primary-400" /> Custom Search
            </h3>
            <div className="space-y-3">
              <textarea 
                value={customPrompt}
                onChange={e => setCustomPrompt(e.target.value)}
                rows={3} 
                className="w-full text-sm font-medium text-white bg-slate-950 px-3 py-2 rounded-md border border-slate-700 focus:border-primary-500 focus:ring-1 focus:ring-primary-500 placeholder-slate-600 resize-none"
                placeholder="E.g., Find me 10 boutique clothing shops in Dhanmondi..."
              />
              <button 
                onClick={() => handleGenerate(customPrompt)}
                disabled={isGenerating || !customPrompt.trim()}
                className="w-full py-2.5 bg-primary-600 hover:bg-primary-500 text-white font-bold text-sm rounded-md transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                {isGenerating ? 'Generating...' : 'Generate Custom Leads'}
              </button>
            </div>
          </div>

          <div className="bg-slate-900 rounded-md border border-slate-800 shadow-md p-5">
            <h3 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-400" /> Suggested Niches
            </h3>
            
            <div className="flex gap-2 mb-4 border-b border-slate-800 pb-2">
              <button 
                onClick={() => setActiveTab('E-commerce')}
                className={`text-xs font-bold px-3 py-1.5 rounded-md transition-colors ${activeTab === 'E-commerce' ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-slate-300'}`}
              >
                E-commerce
              </button>
              <button 
                onClick={() => setActiveTab('Restaurant')}
                className={`text-xs font-bold px-3 py-1.5 rounded-md transition-colors ${activeTab === 'Restaurant' ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-slate-300'}`}
              >
                Restaurant
              </button>
            </div>

            <div className="flex flex-wrap gap-2">
              {PREDEFINED_PROMPTS.filter(p => p.category === activeTab).map((prompt, idx) => (
                <button
                  key={idx}
                  onClick={() => handleGenerate(`${prompt.category} - ${prompt.label}`)}
                  disabled={isGenerating}
                  className="px-3 py-1.5 bg-slate-950 border border-slate-800 hover:border-emerald-500/50 hover:bg-emerald-950/20 text-slate-300 text-xs font-semibold rounded-md transition-colors disabled:opacity-50"
                >
                  {prompt.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Results */}
        <div className="lg:col-span-2">
          <div className="bg-slate-900 rounded-md border border-slate-800 shadow-md overflow-hidden flex flex-col h-[calc(100vh-200px)] min-h-[500px]">
            <div className="px-5 py-4 border-b border-slate-800 bg-slate-900/50 flex items-center justify-between">
              <h3 className="text-sm font-bold text-white">Generated Leads ({generatedLeads.length})</h3>
            </div>
            
            <div className="flex-1 overflow-y-auto p-5">
              {isGenerating ? (
                <div className="h-full flex flex-col items-center justify-center space-y-4">
                  <div className="relative w-16 h-16">
                    <div className="absolute inset-0 border-4 border-slate-800 rounded-full"></div>
                    <div className="absolute inset-0 border-4 border-emerald-500 rounded-full border-t-transparent animate-spin"></div>
                    <Sparkles className="absolute inset-0 m-auto w-6 h-6 text-emerald-400 animate-pulse" />
                  </div>
                  <p className="text-sm text-slate-400 font-medium">Scouting for fresh leads...</p>
                </div>
              ) : generatedLeads.length > 0 ? (
                <div className="space-y-3">
                  {generatedLeads.map((lead, idx) => (
                    <div key={idx} className="bg-slate-950 border border-slate-800 p-4 rounded-md flex flex-col gap-2">
                      <div className="flex justify-between items-start">
                        <h4 className="text-base font-bold text-white">{lead.businessName}</h4>
                        <span className="text-[10px] uppercase tracking-wider font-bold px-2 py-1 bg-slate-800 text-slate-300 rounded-md">
                          {lead.businessType}
                        </span>
                      </div>
                      <div className="grid grid-cols-2 gap-2 text-xs">
                        <p className="text-slate-400"><span className="text-slate-500 dark:text-slate-400">Owner:</span> {lead.ownerName || 'N/A'}</p>
                        <p className="text-slate-400"><span className="text-slate-500 dark:text-slate-400">Phone:</span> {lead.phone || 'N/A'}</p>
                        <p className="text-slate-400"><span className="text-slate-500 dark:text-slate-400">Location:</span> {lead.locationArea || 'N/A'}</p>
                        <p className="text-slate-400"><span className="text-slate-500 dark:text-slate-400">Sub-type:</span> {lead.businessSubType || 'N/A'}</p>
                      </div>
                      {lead.painPoint && (
                        <p className="text-xs text-primary-300 mt-1 bg-primary-950/30 p-2 rounded border border-primary-900/50">
                          <span className="font-bold">Pain Point:</span> {lead.painPoint}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <div className="h-full flex flex-col items-center justify-center space-y-3">
                  <div className="w-16 h-16 rounded-full bg-slate-800 flex items-center justify-center">
                    <Sparkles className="w-8 h-8 text-slate-600 dark:text-slate-400" />
                  </div>
                  <p className="text-sm text-slate-500 dark:text-slate-400 font-medium max-w-xs text-center">
                    Select a category from the left or type a custom prompt to generate potential leads.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Floating Import Button */}
      {generatedLeads.length > 0 && (
        <div className="fixed bottom-6 right-6 z-40 animate-in slide-in-from-bottom-8">
          <button
            onClick={handleImport}
            disabled={isImporting}
            className="flex items-center gap-3 px-6 py-3.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-full shadow-lg shadow-emerald-900/50 font-bold transition-all disabled:opacity-50 hover:-translate-y-1"
          >
            {isImporting ? <Loader2 className="w-5 h-5 animate-spin" /> : <Download className="w-5 h-5" />}
            Import {generatedLeads.length} Leads to CRM
          </button>
        </div>
      )}
    </div>
  );
};
